// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package bbh

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUsernameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsernameRequest) Reset()         { *m = GetUsernameRequest{} }
func (m *GetUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsernameRequest) ProtoMessage()    {}
func (*GetUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *GetUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsernameRequest.Unmarshal(m, b)
}
func (m *GetUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsernameRequest.Marshal(b, m, deterministic)
}
func (m *GetUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsernameRequest.Merge(m, src)
}
func (m *GetUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsernameRequest.Size(m)
}
func (m *GetUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsernameRequest proto.InternalMessageInfo

type GetUsernameReponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsernameReponse) Reset()         { *m = GetUsernameReponse{} }
func (m *GetUsernameReponse) String() string { return proto.CompactTextString(m) }
func (*GetUsernameReponse) ProtoMessage()    {}
func (*GetUsernameReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *GetUsernameReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsernameReponse.Unmarshal(m, b)
}
func (m *GetUsernameReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsernameReponse.Marshal(b, m, deterministic)
}
func (m *GetUsernameReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsernameReponse.Merge(m, src)
}
func (m *GetUsernameReponse) XXX_Size() int {
	return xxx_messageInfo_GetUsernameReponse.Size(m)
}
func (m *GetUsernameReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsernameReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsernameReponse proto.InternalMessageInfo

func (m *GetUsernameReponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetUsernameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUsernameRequest) Reset()         { *m = SetUsernameRequest{} }
func (m *SetUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*SetUsernameRequest) ProtoMessage()    {}
func (*SetUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *SetUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUsernameRequest.Unmarshal(m, b)
}
func (m *SetUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUsernameRequest.Marshal(b, m, deterministic)
}
func (m *SetUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUsernameRequest.Merge(m, src)
}
func (m *SetUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_SetUsernameRequest.Size(m)
}
func (m *SetUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUsernameRequest proto.InternalMessageInfo

func (m *SetUsernameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SetUsernameResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUsernameResponse) Reset()         { *m = SetUsernameResponse{} }
func (m *SetUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*SetUsernameResponse) ProtoMessage()    {}
func (*SetUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *SetUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUsernameResponse.Unmarshal(m, b)
}
func (m *SetUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUsernameResponse.Marshal(b, m, deterministic)
}
func (m *SetUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUsernameResponse.Merge(m, src)
}
func (m *SetUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_SetUsernameResponse.Size(m)
}
func (m *SetUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUsernameResponse proto.InternalMessageInfo

func (m *SetUsernameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetHighscoreRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHighscoreRequest) Reset()         { *m = GetHighscoreRequest{} }
func (m *GetHighscoreRequest) String() string { return proto.CompactTextString(m) }
func (*GetHighscoreRequest) ProtoMessage()    {}
func (*GetHighscoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *GetHighscoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHighscoreRequest.Unmarshal(m, b)
}
func (m *GetHighscoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHighscoreRequest.Marshal(b, m, deterministic)
}
func (m *GetHighscoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHighscoreRequest.Merge(m, src)
}
func (m *GetHighscoreRequest) XXX_Size() int {
	return xxx_messageInfo_GetHighscoreRequest.Size(m)
}
func (m *GetHighscoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHighscoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHighscoreRequest proto.InternalMessageInfo

type GetHighscoreResponse struct {
	Highscores           []*Highscore `protobuf:"bytes,1,rep,name=highscores,proto3" json:"highscores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetHighscoreResponse) Reset()         { *m = GetHighscoreResponse{} }
func (m *GetHighscoreResponse) String() string { return proto.CompactTextString(m) }
func (*GetHighscoreResponse) ProtoMessage()    {}
func (*GetHighscoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{5}
}

func (m *GetHighscoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHighscoreResponse.Unmarshal(m, b)
}
func (m *GetHighscoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHighscoreResponse.Marshal(b, m, deterministic)
}
func (m *GetHighscoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHighscoreResponse.Merge(m, src)
}
func (m *GetHighscoreResponse) XXX_Size() int {
	return xxx_messageInfo_GetHighscoreResponse.Size(m)
}
func (m *GetHighscoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHighscoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHighscoreResponse proto.InternalMessageInfo

func (m *GetHighscoreResponse) GetHighscores() []*Highscore {
	if m != nil {
		return m.Highscores
	}
	return nil
}

type AddBountyRequest struct {
	EntityId             int64    `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBountyRequest) Reset()         { *m = AddBountyRequest{} }
func (m *AddBountyRequest) String() string { return proto.CompactTextString(m) }
func (*AddBountyRequest) ProtoMessage()    {}
func (*AddBountyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{6}
}

func (m *AddBountyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBountyRequest.Unmarshal(m, b)
}
func (m *AddBountyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBountyRequest.Marshal(b, m, deterministic)
}
func (m *AddBountyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBountyRequest.Merge(m, src)
}
func (m *AddBountyRequest) XXX_Size() int {
	return xxx_messageInfo_AddBountyRequest.Size(m)
}
func (m *AddBountyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBountyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBountyRequest proto.InternalMessageInfo

func (m *AddBountyRequest) GetEntityId() int64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *AddBountyRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AddBountyRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddBountyResponse struct {
	Invoice              string   `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBountyResponse) Reset()         { *m = AddBountyResponse{} }
func (m *AddBountyResponse) String() string { return proto.CompactTextString(m) }
func (*AddBountyResponse) ProtoMessage()    {}
func (*AddBountyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{7}
}

func (m *AddBountyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBountyResponse.Unmarshal(m, b)
}
func (m *AddBountyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBountyResponse.Marshal(b, m, deterministic)
}
func (m *AddBountyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBountyResponse.Merge(m, src)
}
func (m *AddBountyResponse) XXX_Size() int {
	return xxx_messageInfo_AddBountyResponse.Size(m)
}
func (m *AddBountyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBountyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBountyResponse proto.InternalMessageInfo

func (m *AddBountyResponse) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

type Highscore struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kills                int32    `protobuf:"varint,2,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths               int32    `protobuf:"varint,3,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Earnings             int64    `protobuf:"varint,4,opt,name=earnings,proto3" json:"earnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Highscore) Reset()         { *m = Highscore{} }
func (m *Highscore) String() string { return proto.CompactTextString(m) }
func (*Highscore) ProtoMessage()    {}
func (*Highscore) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{8}
}

func (m *Highscore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Highscore.Unmarshal(m, b)
}
func (m *Highscore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Highscore.Marshal(b, m, deterministic)
}
func (m *Highscore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Highscore.Merge(m, src)
}
func (m *Highscore) XXX_Size() int {
	return xxx_messageInfo_Highscore.Size(m)
}
func (m *Highscore) XXX_DiscardUnknown() {
	xxx_messageInfo_Highscore.DiscardUnknown(m)
}

var xxx_messageInfo_Highscore proto.InternalMessageInfo

func (m *Highscore) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Highscore) GetKills() int32 {
	if m != nil {
		return m.Kills
	}
	return 0
}

func (m *Highscore) GetDeaths() int32 {
	if m != nil {
		return m.Deaths
	}
	return 0
}

func (m *Highscore) GetEarnings() int64 {
	if m != nil {
		return m.Earnings
	}
	return 0
}

func init() {
	proto.RegisterType((*GetUsernameRequest)(nil), "bbh.GetUsernameRequest")
	proto.RegisterType((*GetUsernameReponse)(nil), "bbh.GetUsernameReponse")
	proto.RegisterType((*SetUsernameRequest)(nil), "bbh.SetUsernameRequest")
	proto.RegisterType((*SetUsernameResponse)(nil), "bbh.SetUsernameResponse")
	proto.RegisterType((*GetHighscoreRequest)(nil), "bbh.GetHighscoreRequest")
	proto.RegisterType((*GetHighscoreResponse)(nil), "bbh.GetHighscoreResponse")
	proto.RegisterType((*AddBountyRequest)(nil), "bbh.AddBountyRequest")
	proto.RegisterType((*AddBountyResponse)(nil), "bbh.AddBountyResponse")
	proto.RegisterType((*Highscore)(nil), "bbh.Highscore")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xbb, 0x6e, 0xea, 0x40,
	0x10, 0x15, 0x98, 0x97, 0x07, 0xee, 0xd5, 0xbd, 0xcb, 0x23, 0x1b, 0xa7, 0x41, 0xae, 0x48, 0x11,
	0x17, 0xa4, 0x4b, 0x93, 0x07, 0x52, 0x48, 0x5a, 0xa3, 0xd4, 0x91, 0x1f, 0x23, 0xbc, 0x0a, 0xac,
	0x89, 0x77, 0x41, 0xe2, 0x3b, 0xf2, 0xc3, 0x91, 0xd7, 0x6b, 0x62, 0x6c, 0xa7, 0xf3, 0x39, 0x73,
	0x76, 0xe6, 0xcc, 0xc3, 0x30, 0x08, 0x36, 0x0c, 0xb9, 0x74, 0x76, 0x49, 0x2c, 0x63, 0x62, 0xf8,
	0x7e, 0x64, 0x8f, 0x80, 0x2c, 0x51, 0xbe, 0x09, 0x4c, 0xb8, 0xb7, 0x45, 0x17, 0x3f, 0xf7, 0x28,
	0xa4, 0x3d, 0x2b, 0xb1, 0xbb, 0x98, 0x0b, 0x24, 0x04, 0x5a, 0x29, 0xa4, 0x8d, 0x69, 0x63, 0x66,
	0xba, 0xea, 0x3b, 0x55, 0xae, 0x2a, 0xef, 0x6b, 0x95, 0xd7, 0x30, 0x3c, 0x53, 0x8a, 0xdf, 0x93,
	0x8e, 0x61, 0xb8, 0x44, 0xf9, 0xc2, 0xd6, 0x91, 0x08, 0xe2, 0xe4, 0xe4, 0xea, 0x19, 0x46, 0xe7,
	0xb4, 0x4e, 0xe1, 0x00, 0x44, 0x39, 0x29, 0x68, 0x63, 0x6a, 0xcc, 0xfa, 0xf3, 0xbf, 0x8e, 0xef,
	0x47, 0xce, 0x8f, 0xb6, 0xa0, 0xb0, 0x3d, 0xf8, 0xf7, 0x18, 0x86, 0x4f, 0xf1, 0x9e, 0xcb, 0x63,
	0xee, 0xf8, 0x0a, 0x4c, 0xe4, 0x92, 0xc9, 0xe3, 0x3b, 0x0b, 0x95, 0x17, 0xc3, 0xed, 0x65, 0xc4,
	0x6b, 0x48, 0x26, 0xd0, 0xf1, 0xb6, 0xa9, 0x9c, 0x36, 0x55, 0x44, 0x23, 0x42, 0xa1, 0xbb, 0x45,
	0x21, 0xbc, 0x35, 0x52, 0x43, 0xd9, 0xcf, 0xa1, 0x7d, 0x03, 0xff, 0x0b, 0x25, 0xb4, 0x4f, 0x0a,
	0x5d, 0xc6, 0x0f, 0x31, 0x0b, 0xf2, 0x6e, 0x73, 0x68, 0x33, 0x30, 0x4f, 0x56, 0xeb, 0x26, 0x42,
	0x46, 0xd0, 0xfe, 0x60, 0x9b, 0x8d, 0x50, 0x06, 0xda, 0x6e, 0x06, 0x52, 0x5f, 0x21, 0x7a, 0x32,
	0x12, 0xaa, 0x7c, 0xdb, 0xd5, 0x88, 0x58, 0xd0, 0x43, 0x2f, 0xe1, 0x8c, 0xaf, 0x05, 0x6d, 0xe9,
	0x5e, 0x34, 0x9e, 0x7f, 0x35, 0xe1, 0xcf, 0x42, 0x9d, 0xc1, 0x0a, 0x93, 0x03, 0x0b, 0x90, 0xdc,
	0x43, 0xbf, 0xb0, 0x6c, 0x72, 0xa1, 0x26, 0x57, 0x3d, 0x0a, 0xab, 0x26, 0x90, 0xf5, 0xf5, 0x00,
	0xfd, 0x55, 0x25, 0x41, 0xf5, 0x2a, 0x2c, 0x5a, 0x0d, 0xe8, 0xc9, 0x2c, 0x60, 0x50, 0xdc, 0x2c,
	0xa1, 0x79, 0xa9, 0xf2, 0x0d, 0x58, 0x97, 0x35, 0x11, 0x9d, 0xe4, 0x0e, 0xcc, 0xd3, 0xcc, 0xc9,
	0x58, 0xe9, 0xca, 0x6b, 0xb6, 0x26, 0x65, 0x3a, 0x7b, 0xeb, 0x77, 0xd4, 0x2f, 0x71, 0xfb, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x84, 0xc0, 0x96, 0x5e, 0x22, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	GetUsername(ctx context.Context, in *GetUsernameRequest, opts ...grpc.CallOption) (*GetUsernameReponse, error)
	SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...grpc.CallOption) (*SetUsernameResponse, error)
	GetHighscore(ctx context.Context, in *GetHighscoreRequest, opts ...grpc.CallOption) (*GetHighscoreResponse, error)
	AddBounty(ctx context.Context, in *AddBountyRequest, opts ...grpc.CallOption) (*AddBountyResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) GetUsername(ctx context.Context, in *GetUsernameRequest, opts ...grpc.CallOption) (*GetUsernameReponse, error) {
	out := new(GetUsernameReponse)
	err := c.cc.Invoke(ctx, "/bbh.ClientService/GetUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) SetUsername(ctx context.Context, in *SetUsernameRequest, opts ...grpc.CallOption) (*SetUsernameResponse, error) {
	out := new(SetUsernameResponse)
	err := c.cc.Invoke(ctx, "/bbh.ClientService/SetUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) GetHighscore(ctx context.Context, in *GetHighscoreRequest, opts ...grpc.CallOption) (*GetHighscoreResponse, error) {
	out := new(GetHighscoreResponse)
	err := c.cc.Invoke(ctx, "/bbh.ClientService/GetHighscore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) AddBounty(ctx context.Context, in *AddBountyRequest, opts ...grpc.CallOption) (*AddBountyResponse, error) {
	out := new(AddBountyResponse)
	err := c.cc.Invoke(ctx, "/bbh.ClientService/AddBounty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	GetUsername(context.Context, *GetUsernameRequest) (*GetUsernameReponse, error)
	SetUsername(context.Context, *SetUsernameRequest) (*SetUsernameResponse, error)
	GetHighscore(context.Context, *GetHighscoreRequest) (*GetHighscoreResponse, error)
	AddBounty(context.Context, *AddBountyRequest) (*AddBountyResponse, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) GetUsername(ctx context.Context, req *GetUsernameRequest) (*GetUsernameReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsername not implemented")
}
func (*UnimplementedClientServiceServer) SetUsername(ctx context.Context, req *SetUsernameRequest) (*SetUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUsername not implemented")
}
func (*UnimplementedClientServiceServer) GetHighscore(ctx context.Context, req *GetHighscoreRequest) (*GetHighscoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHighscore not implemented")
}
func (*UnimplementedClientServiceServer) AddBounty(ctx context.Context, req *AddBountyRequest) (*AddBountyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBounty not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_GetUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bbh.ClientService/GetUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetUsername(ctx, req.(*GetUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_SetUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).SetUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bbh.ClientService/SetUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).SetUsername(ctx, req.(*SetUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_GetHighscore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighscoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).GetHighscore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bbh.ClientService/GetHighscore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).GetHighscore(ctx, req.(*GetHighscoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_AddBounty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBountyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).AddBounty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bbh.ClientService/AddBounty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).AddBounty(ctx, req.(*AddBountyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bbh.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsername",
			Handler:    _ClientService_GetUsername_Handler,
		},
		{
			MethodName: "SetUsername",
			Handler:    _ClientService_SetUsername_Handler,
		},
		{
			MethodName: "GetHighscore",
			Handler:    _ClientService_GetHighscore_Handler,
		},
		{
			MethodName: "AddBounty",
			Handler:    _ClientService_AddBounty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
