// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameserver.proto

package bbh

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerInfoEvent_EventType int32

const (
	PlayerInfoEvent_HEARTBEAT  PlayerInfoEvent_EventType = 0
	PlayerInfoEvent_DISCONNECT PlayerInfoEvent_EventType = 1
)

var PlayerInfoEvent_EventType_name = map[int32]string{
	0: "HEARTBEAT",
	1: "DISCONNECT",
}

var PlayerInfoEvent_EventType_value = map[string]int32{
	"HEARTBEAT":  0,
	"DISCONNECT": 1,
}

func (x PlayerInfoEvent_EventType) String() string {
	return proto.EnumName(PlayerInfoEvent_EventType_name, int32(x))
}

func (PlayerInfoEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{4, 0}
}

type EventStreamRequest struct {
	// Types that are valid to be assigned to Event:
	//	*EventStreamRequest_Kill
	//	*EventStreamRequest_Earnings
	//	*EventStreamRequest_PlayerInfo
	Event                isEventStreamRequest_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EventStreamRequest) Reset()         { *m = EventStreamRequest{} }
func (m *EventStreamRequest) String() string { return proto.CompactTextString(m) }
func (*EventStreamRequest) ProtoMessage()    {}
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{0}
}

func (m *EventStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStreamRequest.Unmarshal(m, b)
}
func (m *EventStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStreamRequest.Marshal(b, m, deterministic)
}
func (m *EventStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStreamRequest.Merge(m, src)
}
func (m *EventStreamRequest) XXX_Size() int {
	return xxx_messageInfo_EventStreamRequest.Size(m)
}
func (m *EventStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventStreamRequest proto.InternalMessageInfo

type isEventStreamRequest_Event interface {
	isEventStreamRequest_Event()
}

type EventStreamRequest_Kill struct {
	Kill *KillEvent `protobuf:"bytes,1,opt,name=kill,proto3,oneof"`
}

type EventStreamRequest_Earnings struct {
	Earnings *EarningsEvent `protobuf:"bytes,2,opt,name=earnings,proto3,oneof"`
}

type EventStreamRequest_PlayerInfo struct {
	PlayerInfo *PlayerInfoEvent `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3,oneof"`
}

func (*EventStreamRequest_Kill) isEventStreamRequest_Event() {}

func (*EventStreamRequest_Earnings) isEventStreamRequest_Event() {}

func (*EventStreamRequest_PlayerInfo) isEventStreamRequest_Event() {}

func (m *EventStreamRequest) GetEvent() isEventStreamRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventStreamRequest) GetKill() *KillEvent {
	if x, ok := m.GetEvent().(*EventStreamRequest_Kill); ok {
		return x.Kill
	}
	return nil
}

func (m *EventStreamRequest) GetEarnings() *EarningsEvent {
	if x, ok := m.GetEvent().(*EventStreamRequest_Earnings); ok {
		return x.Earnings
	}
	return nil
}

func (m *EventStreamRequest) GetPlayerInfo() *PlayerInfoEvent {
	if x, ok := m.GetEvent().(*EventStreamRequest_PlayerInfo); ok {
		return x.PlayerInfo
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventStreamRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventStreamRequest_Kill)(nil),
		(*EventStreamRequest_Earnings)(nil),
		(*EventStreamRequest_PlayerInfo)(nil),
	}
}

type EventStreamResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStreamResponse) Reset()         { *m = EventStreamResponse{} }
func (m *EventStreamResponse) String() string { return proto.CompactTextString(m) }
func (*EventStreamResponse) ProtoMessage()    {}
func (*EventStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{1}
}

func (m *EventStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStreamResponse.Unmarshal(m, b)
}
func (m *EventStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStreamResponse.Marshal(b, m, deterministic)
}
func (m *EventStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStreamResponse.Merge(m, src)
}
func (m *EventStreamResponse) XXX_Size() int {
	return xxx_messageInfo_EventStreamResponse.Size(m)
}
func (m *EventStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventStreamResponse proto.InternalMessageInfo

type KillEvent struct {
	Killer               string   `protobuf:"bytes,1,opt,name=killer,proto3" json:"killer,omitempty"`
	Victim               string   `protobuf:"bytes,2,opt,name=victim,proto3" json:"victim,omitempty"`
	Cause                string   `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillEvent) Reset()         { *m = KillEvent{} }
func (m *KillEvent) String() string { return proto.CompactTextString(m) }
func (*KillEvent) ProtoMessage()    {}
func (*KillEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{2}
}

func (m *KillEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillEvent.Unmarshal(m, b)
}
func (m *KillEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillEvent.Marshal(b, m, deterministic)
}
func (m *KillEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillEvent.Merge(m, src)
}
func (m *KillEvent) XXX_Size() int {
	return xxx_messageInfo_KillEvent.Size(m)
}
func (m *KillEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_KillEvent.DiscardUnknown(m)
}

var xxx_messageInfo_KillEvent proto.InternalMessageInfo

func (m *KillEvent) GetKiller() string {
	if m != nil {
		return m.Killer
	}
	return ""
}

func (m *KillEvent) GetVictim() string {
	if m != nil {
		return m.Victim
	}
	return ""
}

func (m *KillEvent) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type EarningsEvent struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Amt                  int64    `protobuf:"varint,2,opt,name=amt,proto3" json:"amt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EarningsEvent) Reset()         { *m = EarningsEvent{} }
func (m *EarningsEvent) String() string { return proto.CompactTextString(m) }
func (*EarningsEvent) ProtoMessage()    {}
func (*EarningsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{3}
}

func (m *EarningsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EarningsEvent.Unmarshal(m, b)
}
func (m *EarningsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EarningsEvent.Marshal(b, m, deterministic)
}
func (m *EarningsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EarningsEvent.Merge(m, src)
}
func (m *EarningsEvent) XXX_Size() int {
	return xxx_messageInfo_EarningsEvent.Size(m)
}
func (m *EarningsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EarningsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EarningsEvent proto.InternalMessageInfo

func (m *EarningsEvent) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *EarningsEvent) GetAmt() int64 {
	if m != nil {
		return m.Amt
	}
	return 0
}

type PlayerInfoEvent struct {
	User                 string                    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	EventType            PlayerInfoEvent_EventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=bbh.PlayerInfoEvent_EventType" json:"event_type,omitempty"`
	CurrentBounty        int64                     `protobuf:"varint,3,opt,name=current_bounty,json=currentBounty,proto3" json:"current_bounty,omitempty"`
	CurrentKills         int32                     `protobuf:"varint,4,opt,name=current_kills,json=currentKills,proto3" json:"current_kills,omitempty"`
	CurrentDeaths        int32                     `protobuf:"varint,5,opt,name=current_deaths,json=currentDeaths,proto3" json:"current_deaths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PlayerInfoEvent) Reset()         { *m = PlayerInfoEvent{} }
func (m *PlayerInfoEvent) String() string { return proto.CompactTextString(m) }
func (*PlayerInfoEvent) ProtoMessage()    {}
func (*PlayerInfoEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{4}
}

func (m *PlayerInfoEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfoEvent.Unmarshal(m, b)
}
func (m *PlayerInfoEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfoEvent.Marshal(b, m, deterministic)
}
func (m *PlayerInfoEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfoEvent.Merge(m, src)
}
func (m *PlayerInfoEvent) XXX_Size() int {
	return xxx_messageInfo_PlayerInfoEvent.Size(m)
}
func (m *PlayerInfoEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfoEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfoEvent proto.InternalMessageInfo

func (m *PlayerInfoEvent) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PlayerInfoEvent) GetEventType() PlayerInfoEvent_EventType {
	if m != nil {
		return m.EventType
	}
	return PlayerInfoEvent_HEARTBEAT
}

func (m *PlayerInfoEvent) GetCurrentBounty() int64 {
	if m != nil {
		return m.CurrentBounty
	}
	return 0
}

func (m *PlayerInfoEvent) GetCurrentKills() int32 {
	if m != nil {
		return m.CurrentKills
	}
	return 0
}

func (m *PlayerInfoEvent) GetCurrentDeaths() int32 {
	if m != nil {
		return m.CurrentDeaths
	}
	return 0
}

type GetUserRequest struct {
	Pubkey               string   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pubkey               string   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_97a199f3261f0fcf, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func init() {
	proto.RegisterEnum("bbh.PlayerInfoEvent_EventType", PlayerInfoEvent_EventType_name, PlayerInfoEvent_EventType_value)
	proto.RegisterType((*EventStreamRequest)(nil), "bbh.EventStreamRequest")
	proto.RegisterType((*EventStreamResponse)(nil), "bbh.EventStreamResponse")
	proto.RegisterType((*KillEvent)(nil), "bbh.KillEvent")
	proto.RegisterType((*EarningsEvent)(nil), "bbh.EarningsEvent")
	proto.RegisterType((*PlayerInfoEvent)(nil), "bbh.PlayerInfoEvent")
	proto.RegisterType((*GetUserRequest)(nil), "bbh.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "bbh.GetUserResponse")
	proto.RegisterType((*User)(nil), "bbh.User")
}

func init() { proto.RegisterFile("gameserver.proto", fileDescriptor_97a199f3261f0fcf) }

var fileDescriptor_97a199f3261f0fcf = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xf3, 0x55, 0x3c, 0x21, 0x69, 0x34, 0x0d, 0xc5, 0xaa, 0x04, 0xaa, 0x0c, 0x48, 0x11,
	0x87, 0xa8, 0x0a, 0x20, 0x4e, 0x1c, 0x9a, 0x36, 0x6a, 0x2b, 0xa4, 0x02, 0x9b, 0x70, 0x8e, 0xec,
	0x30, 0x6d, 0xac, 0xc6, 0x1f, 0xec, 0xae, 0x23, 0xf9, 0xcc, 0x81, 0x7f, 0xc3, 0x6f, 0x44, 0x3b,
	0xfe, 0x90, 0xd3, 0xf6, 0x62, 0xcd, 0x3c, 0xbf, 0x99, 0x7d, 0xf3, 0x76, 0x16, 0x06, 0x77, 0x5e,
	0x48, 0x8a, 0xe4, 0x96, 0xe4, 0x38, 0x91, 0xb1, 0x8e, 0xb1, 0xe9, 0xfb, 0x6b, 0xf7, 0x9f, 0x05,
	0x38, 0xdb, 0x52, 0xa4, 0xe7, 0x5a, 0x92, 0x17, 0x0a, 0xfa, 0x9d, 0x92, 0xd2, 0xf8, 0x16, 0x5a,
	0xf7, 0xc1, 0x66, 0xe3, 0x58, 0x27, 0xd6, 0xa8, 0x3b, 0xe9, 0x8f, 0x7d, 0x7f, 0x3d, 0xfe, 0x1a,
	0x6c, 0x36, 0x4c, 0xbd, 0xda, 0x13, 0xfc, 0x17, 0x4f, 0xe1, 0x19, 0x79, 0x32, 0x0a, 0xa2, 0x3b,
	0xe5, 0x34, 0x98, 0x89, 0xcc, 0x9c, 0x15, 0x60, 0xc9, 0xae, 0x58, 0xf8, 0x19, 0xba, 0xc9, 0xc6,
	0xcb, 0x48, 0x2e, 0x83, 0xe8, 0x36, 0x76, 0x9a, 0x5c, 0x34, 0xe4, 0xa2, 0xef, 0x8c, 0x5f, 0x47,
	0xb7, 0x71, 0x59, 0x06, 0x49, 0x05, 0x4d, 0xf7, 0xa1, 0x4d, 0x06, 0x76, 0x5f, 0xc0, 0xe1, 0x8e,
	0x5e, 0x95, 0xc4, 0x91, 0x22, 0xf7, 0x07, 0xd8, 0x95, 0x3e, 0x3c, 0x82, 0x8e, 0xd1, 0x47, 0x92,
	0xf5, 0xdb, 0xa2, 0xc8, 0x0c, 0xbe, 0x0d, 0x56, 0x3a, 0x08, 0x59, 0xad, 0x2d, 0x8a, 0x0c, 0x87,
	0xd0, 0x5e, 0x79, 0xa9, 0x22, 0xd6, 0x63, 0x8b, 0x3c, 0x71, 0x3f, 0x41, 0x6f, 0x67, 0x10, 0x44,
	0x68, 0xa5, 0xaa, 0x6a, 0xca, 0x31, 0x0e, 0xa0, 0xe9, 0x85, 0x9a, 0xfb, 0x35, 0x85, 0x09, 0xdd,
	0x3f, 0x0d, 0x38, 0x78, 0x30, 0xcb, 0x93, 0x95, 0x5f, 0x00, 0x78, 0xa2, 0xa5, 0xce, 0x12, 0xe2,
	0x06, 0xfd, 0xc9, 0xeb, 0xa7, 0x9c, 0x18, 0xf3, 0x77, 0x91, 0x25, 0x24, 0x6c, 0x2a, 0x43, 0x7c,
	0x07, 0xfd, 0x55, 0x2a, 0xa5, 0x69, 0xe0, 0xc7, 0x69, 0xa4, 0x33, 0x16, 0xdf, 0x14, 0xbd, 0x02,
	0x9d, 0x32, 0x88, 0x6f, 0xa0, 0x04, 0x96, 0xc6, 0x04, 0xe5, 0xb4, 0x4e, 0xac, 0x51, 0x5b, 0x3c,
	0x2f, 0x40, 0xe3, 0x99, 0xaa, 0xf7, 0xfa, 0x45, 0x9e, 0x5e, 0x2b, 0xa7, 0xcd, 0xac, 0xb2, 0xf4,
	0x82, 0x41, 0xf7, 0x3d, 0xd8, 0x95, 0x14, 0xec, 0x81, 0x7d, 0x35, 0x3b, 0x13, 0x8b, 0xe9, 0xec,
	0x6c, 0x31, 0xd8, 0xc3, 0x3e, 0xc0, 0xc5, 0xf5, 0xfc, 0xfc, 0xdb, 0xcd, 0xcd, 0xec, 0x7c, 0x31,
	0xb0, 0xdc, 0x11, 0xf4, 0x2f, 0x49, 0xff, 0x54, 0x24, 0xcb, 0x95, 0x3a, 0x82, 0x4e, 0x92, 0xfa,
	0xf7, 0x94, 0x95, 0x97, 0x92, 0x67, 0xee, 0x29, 0x1c, 0x54, 0xcc, 0xfc, 0x32, 0xf1, 0x55, 0xcd,
	0xae, 0xee, 0xc4, 0x66, 0x53, 0x98, 0xc0, 0xb0, 0x3b, 0x81, 0x96, 0xc9, 0x8c, 0xab, 0x91, 0x17,
	0x52, 0xe9, 0xaa, 0x89, 0x6b, 0xa7, 0x34, 0xea, 0xa7, 0x4c, 0xfe, 0x5a, 0xd0, 0xbd, 0xf4, 0x42,
	0x9a, 0x93, 0xdc, 0x06, 0x2b, 0xc2, 0x29, 0x74, 0x6b, 0x6b, 0x84, 0x2f, 0xf3, 0xbd, 0x7d, 0xf4,
	0x10, 0x8e, 0x9d, 0xc7, 0x3f, 0x72, 0x91, 0x23, 0x0b, 0x3f, 0xc2, 0x7e, 0xa1, 0x1c, 0x0f, 0x99,
	0xb6, 0x3b, 0xf1, 0xf1, 0x70, 0x17, 0xcc, 0xeb, 0xfc, 0x0e, 0xbf, 0xbe, 0x0f, 0xff, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x41, 0x58, 0x0e, 0xdf, 0x91, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	EventStream(ctx context.Context, opts ...grpc.CallOption) (GameService_EventStreamClient, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (GameService_EventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GameService_serviceDesc.Streams[0], "/bbh.GameService/EventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceEventStreamClient{stream}
	return x, nil
}

type GameService_EventStreamClient interface {
	Send(*EventStreamRequest) error
	CloseAndRecv() (*EventStreamResponse, error)
	grpc.ClientStream
}

type gameServiceEventStreamClient struct {
	grpc.ClientStream
}

func (x *gameServiceEventStreamClient) Send(m *EventStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServiceEventStreamClient) CloseAndRecv() (*EventStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EventStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/bbh.GameService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	EventStream(GameService_EventStreamServer) error
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// UnimplementedGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) EventStream(srv GameService_EventStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EventStream not implemented")
}
func (*UnimplementedGameServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).EventStream(&gameServiceEventStreamServer{stream})
}

type GameService_EventStreamServer interface {
	SendAndClose(*EventStreamResponse) error
	Recv() (*EventStreamRequest, error)
	grpc.ServerStream
}

type gameServiceEventStreamServer struct {
	grpc.ServerStream
}

func (x *gameServiceEventStreamServer) SendAndClose(m *EventStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServiceEventStreamServer) Recv() (*EventStreamRequest, error) {
	m := new(EventStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GameService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bbh.GameService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bbh.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _GameService_GetUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _GameService_EventStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "gameserver.proto",
}
