// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bbh-backend/client.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Bbhrpc {
  public static partial class GameClientService
  {
    static readonly string __ServiceName = "bbhrpc.GameClientService";

    static readonly grpc::Marshaller<global::Bbhrpc.GetUsernameRequest> __Marshaller_bbhrpc_GetUsernameRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetUsernameRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetUsernameReponse> __Marshaller_bbhrpc_GetUsernameReponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetUsernameReponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.SetUsernameRequest> __Marshaller_bbhrpc_SetUsernameRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.SetUsernameRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.SetUsernameResponse> __Marshaller_bbhrpc_SetUsernameResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.SetUsernameResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Bbhrpc.GetUsernameRequest, global::Bbhrpc.GetUsernameReponse> __Method_GetUsername = new grpc::Method<global::Bbhrpc.GetUsernameRequest, global::Bbhrpc.GetUsernameReponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUsername",
        __Marshaller_bbhrpc_GetUsernameRequest,
        __Marshaller_bbhrpc_GetUsernameReponse);

    static readonly grpc::Method<global::Bbhrpc.SetUsernameRequest, global::Bbhrpc.SetUsernameResponse> __Method_SetUsername = new grpc::Method<global::Bbhrpc.SetUsernameRequest, global::Bbhrpc.SetUsernameResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetUsername",
        __Marshaller_bbhrpc_SetUsernameRequest,
        __Marshaller_bbhrpc_SetUsernameResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Bbhrpc.ClientReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GameClientService</summary>
    [grpc::BindServiceMethod(typeof(GameClientService), "BindService")]
    public abstract partial class GameClientServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetUsernameReponse> GetUsername(global::Bbhrpc.GetUsernameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.SetUsernameResponse> SetUsername(global::Bbhrpc.SetUsernameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GameClientService</summary>
    public partial class GameClientServiceClient : grpc::ClientBase<GameClientServiceClient>
    {
      /// <summary>Creates a new client for GameClientService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GameClientServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GameClientService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GameClientServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GameClientServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GameClientServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Bbhrpc.GetUsernameReponse GetUsername(global::Bbhrpc.GetUsernameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUsername(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetUsernameReponse GetUsername(global::Bbhrpc.GetUsernameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUsername, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetUsernameReponse> GetUsernameAsync(global::Bbhrpc.GetUsernameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUsernameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetUsernameReponse> GetUsernameAsync(global::Bbhrpc.GetUsernameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUsername, null, options, request);
      }
      public virtual global::Bbhrpc.SetUsernameResponse SetUsername(global::Bbhrpc.SetUsernameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUsername(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.SetUsernameResponse SetUsername(global::Bbhrpc.SetUsernameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SetUsername, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.SetUsernameResponse> SetUsernameAsync(global::Bbhrpc.SetUsernameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetUsernameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.SetUsernameResponse> SetUsernameAsync(global::Bbhrpc.SetUsernameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SetUsername, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GameClientServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GameClientServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GameClientServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetUsername, serviceImpl.GetUsername)
          .AddMethod(__Method_SetUsername, serviceImpl.SetUsername).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GameClientServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetUsername, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetUsernameRequest, global::Bbhrpc.GetUsernameReponse>(serviceImpl.GetUsername));
      serviceBinder.AddMethod(__Method_SetUsername, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.SetUsernameRequest, global::Bbhrpc.SetUsernameResponse>(serviceImpl.SetUsername));
    }

  }
  public static partial class AdvertiserService
  {
    static readonly string __ServiceName = "bbhrpc.AdvertiserService";

    static readonly grpc::Marshaller<global::Bbhrpc.CreateAdvertiserRequest> __Marshaller_bbhrpc_CreateAdvertiserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.CreateAdvertiserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.CreateAdvertiserResponse> __Marshaller_bbhrpc_CreateAdvertiserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.CreateAdvertiserResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.DepositAdvertiserRequest> __Marshaller_bbhrpc_DepositAdvertiserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.DepositAdvertiserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.DepositAdvertiserResponse> __Marshaller_bbhrpc_DepositAdvertiserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.DepositAdvertiserResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.ListAdvertisersRequest> __Marshaller_bbhrpc_ListAdvertisersRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListAdvertisersRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.ListAdvertiserResponse> __Marshaller_bbhrpc_ListAdvertiserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListAdvertiserResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Bbhrpc.CreateAdvertiserRequest, global::Bbhrpc.CreateAdvertiserResponse> __Method_CreateAdvertiser = new grpc::Method<global::Bbhrpc.CreateAdvertiserRequest, global::Bbhrpc.CreateAdvertiserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateAdvertiser",
        __Marshaller_bbhrpc_CreateAdvertiserRequest,
        __Marshaller_bbhrpc_CreateAdvertiserResponse);

    static readonly grpc::Method<global::Bbhrpc.DepositAdvertiserRequest, global::Bbhrpc.DepositAdvertiserResponse> __Method_DepositAdvertiser = new grpc::Method<global::Bbhrpc.DepositAdvertiserRequest, global::Bbhrpc.DepositAdvertiserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DepositAdvertiser",
        __Marshaller_bbhrpc_DepositAdvertiserRequest,
        __Marshaller_bbhrpc_DepositAdvertiserResponse);

    static readonly grpc::Method<global::Bbhrpc.ListAdvertisersRequest, global::Bbhrpc.ListAdvertiserResponse> __Method_ListAdvertisers = new grpc::Method<global::Bbhrpc.ListAdvertisersRequest, global::Bbhrpc.ListAdvertiserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListAdvertisers",
        __Marshaller_bbhrpc_ListAdvertisersRequest,
        __Marshaller_bbhrpc_ListAdvertiserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Bbhrpc.ClientReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of AdvertiserService</summary>
    [grpc::BindServiceMethod(typeof(AdvertiserService), "BindService")]
    public abstract partial class AdvertiserServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.CreateAdvertiserResponse> CreateAdvertiser(global::Bbhrpc.CreateAdvertiserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.DepositAdvertiserResponse> DepositAdvertiser(global::Bbhrpc.DepositAdvertiserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.ListAdvertiserResponse> ListAdvertisers(global::Bbhrpc.ListAdvertisersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AdvertiserService</summary>
    public partial class AdvertiserServiceClient : grpc::ClientBase<AdvertiserServiceClient>
    {
      /// <summary>Creates a new client for AdvertiserService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AdvertiserServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AdvertiserService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AdvertiserServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AdvertiserServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AdvertiserServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Bbhrpc.CreateAdvertiserResponse CreateAdvertiser(global::Bbhrpc.CreateAdvertiserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAdvertiser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.CreateAdvertiserResponse CreateAdvertiser(global::Bbhrpc.CreateAdvertiserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateAdvertiser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.CreateAdvertiserResponse> CreateAdvertiserAsync(global::Bbhrpc.CreateAdvertiserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateAdvertiserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.CreateAdvertiserResponse> CreateAdvertiserAsync(global::Bbhrpc.CreateAdvertiserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateAdvertiser, null, options, request);
      }
      public virtual global::Bbhrpc.DepositAdvertiserResponse DepositAdvertiser(global::Bbhrpc.DepositAdvertiserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DepositAdvertiser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.DepositAdvertiserResponse DepositAdvertiser(global::Bbhrpc.DepositAdvertiserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DepositAdvertiser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.DepositAdvertiserResponse> DepositAdvertiserAsync(global::Bbhrpc.DepositAdvertiserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DepositAdvertiserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.DepositAdvertiserResponse> DepositAdvertiserAsync(global::Bbhrpc.DepositAdvertiserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DepositAdvertiser, null, options, request);
      }
      public virtual global::Bbhrpc.ListAdvertiserResponse ListAdvertisers(global::Bbhrpc.ListAdvertisersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListAdvertisers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.ListAdvertiserResponse ListAdvertisers(global::Bbhrpc.ListAdvertisersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListAdvertisers, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListAdvertiserResponse> ListAdvertisersAsync(global::Bbhrpc.ListAdvertisersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListAdvertisersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListAdvertiserResponse> ListAdvertisersAsync(global::Bbhrpc.ListAdvertisersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListAdvertisers, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AdvertiserServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AdvertiserServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AdvertiserServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateAdvertiser, serviceImpl.CreateAdvertiser)
          .AddMethod(__Method_DepositAdvertiser, serviceImpl.DepositAdvertiser)
          .AddMethod(__Method_ListAdvertisers, serviceImpl.ListAdvertisers).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AdvertiserServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateAdvertiser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.CreateAdvertiserRequest, global::Bbhrpc.CreateAdvertiserResponse>(serviceImpl.CreateAdvertiser));
      serviceBinder.AddMethod(__Method_DepositAdvertiser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.DepositAdvertiserRequest, global::Bbhrpc.DepositAdvertiserResponse>(serviceImpl.DepositAdvertiser));
      serviceBinder.AddMethod(__Method_ListAdvertisers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.ListAdvertisersRequest, global::Bbhrpc.ListAdvertiserResponse>(serviceImpl.ListAdvertisers));
    }

  }
  public static partial class PublicService
  {
    static readonly string __ServiceName = "bbhrpc.PublicService";

    static readonly grpc::Marshaller<global::Bbhrpc.GetRankingInfoRequest> __Marshaller_bbhrpc_GetRankingInfoRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetRankingInfoRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetRankingInfoResponse> __Marshaller_bbhrpc_GetRankingInfoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetRankingInfoResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetRankingRequest> __Marshaller_bbhrpc_GetRankingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetRankingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetRankingResponse> __Marshaller_bbhrpc_GetRankingResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetRankingResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.ListRankingsRequest> __Marshaller_bbhrpc_ListRankingsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListRankingsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.ListRankingsResponse> __Marshaller_bbhrpc_ListRankingsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListRankingsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.AddBountyRequest> __Marshaller_bbhrpc_AddBountyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.AddBountyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.AddBountyResponse> __Marshaller_bbhrpc_AddBountyResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.AddBountyResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.ListOnlineRequest> __Marshaller_bbhrpc_ListOnlineRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListOnlineRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.ListOnlineResponse> __Marshaller_bbhrpc_ListOnlineResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListOnlineResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetInfoRequest> __Marshaller_bbhrpc_GetInfoRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetInfoRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetInfoResponse> __Marshaller_bbhrpc_GetInfoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetInfoResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.SubscribeInvoiceStreamRequest> __Marshaller_bbhrpc_SubscribeInvoiceStreamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.SubscribeInvoiceStreamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.SubscribeInvioceStreamResponse> __Marshaller_bbhrpc_SubscribeInvioceStreamResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.SubscribeInvioceStreamResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Bbhrpc.GetRankingInfoRequest, global::Bbhrpc.GetRankingInfoResponse> __Method_GetRankingInfo = new grpc::Method<global::Bbhrpc.GetRankingInfoRequest, global::Bbhrpc.GetRankingInfoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRankingInfo",
        __Marshaller_bbhrpc_GetRankingInfoRequest,
        __Marshaller_bbhrpc_GetRankingInfoResponse);

    static readonly grpc::Method<global::Bbhrpc.GetRankingRequest, global::Bbhrpc.GetRankingResponse> __Method_GetRanking = new grpc::Method<global::Bbhrpc.GetRankingRequest, global::Bbhrpc.GetRankingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRanking",
        __Marshaller_bbhrpc_GetRankingRequest,
        __Marshaller_bbhrpc_GetRankingResponse);

    static readonly grpc::Method<global::Bbhrpc.ListRankingsRequest, global::Bbhrpc.ListRankingsResponse> __Method_ListRankings = new grpc::Method<global::Bbhrpc.ListRankingsRequest, global::Bbhrpc.ListRankingsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListRankings",
        __Marshaller_bbhrpc_ListRankingsRequest,
        __Marshaller_bbhrpc_ListRankingsResponse);

    static readonly grpc::Method<global::Bbhrpc.AddBountyRequest, global::Bbhrpc.AddBountyResponse> __Method_AddBounty = new grpc::Method<global::Bbhrpc.AddBountyRequest, global::Bbhrpc.AddBountyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddBounty",
        __Marshaller_bbhrpc_AddBountyRequest,
        __Marshaller_bbhrpc_AddBountyResponse);

    static readonly grpc::Method<global::Bbhrpc.ListOnlineRequest, global::Bbhrpc.ListOnlineResponse> __Method_ListOnline = new grpc::Method<global::Bbhrpc.ListOnlineRequest, global::Bbhrpc.ListOnlineResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListOnline",
        __Marshaller_bbhrpc_ListOnlineRequest,
        __Marshaller_bbhrpc_ListOnlineResponse);

    static readonly grpc::Method<global::Bbhrpc.GetInfoRequest, global::Bbhrpc.GetInfoResponse> __Method_GetInfo = new grpc::Method<global::Bbhrpc.GetInfoRequest, global::Bbhrpc.GetInfoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetInfo",
        __Marshaller_bbhrpc_GetInfoRequest,
        __Marshaller_bbhrpc_GetInfoResponse);

    static readonly grpc::Method<global::Bbhrpc.SubscribeInvoiceStreamRequest, global::Bbhrpc.SubscribeInvioceStreamResponse> __Method_SubscribeInvoiceStream = new grpc::Method<global::Bbhrpc.SubscribeInvoiceStreamRequest, global::Bbhrpc.SubscribeInvioceStreamResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeInvoiceStream",
        __Marshaller_bbhrpc_SubscribeInvoiceStreamRequest,
        __Marshaller_bbhrpc_SubscribeInvioceStreamResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Bbhrpc.ClientReflection.Descriptor.Services[2]; }
    }

    /// <summary>Base class for server-side implementations of PublicService</summary>
    [grpc::BindServiceMethod(typeof(PublicService), "BindService")]
    public abstract partial class PublicServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetRankingInfoResponse> GetRankingInfo(global::Bbhrpc.GetRankingInfoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetRankingResponse> GetRanking(global::Bbhrpc.GetRankingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.ListRankingsResponse> ListRankings(global::Bbhrpc.ListRankingsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.AddBountyResponse> AddBounty(global::Bbhrpc.AddBountyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.ListOnlineResponse> ListOnline(global::Bbhrpc.ListOnlineRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetInfoResponse> GetInfo(global::Bbhrpc.GetInfoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SubscribeInvoiceStream(global::Bbhrpc.SubscribeInvoiceStreamRequest request, grpc::IServerStreamWriter<global::Bbhrpc.SubscribeInvioceStreamResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PublicService</summary>
    public partial class PublicServiceClient : grpc::ClientBase<PublicServiceClient>
    {
      /// <summary>Creates a new client for PublicService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PublicServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PublicService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PublicServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PublicServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PublicServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Bbhrpc.GetRankingInfoResponse GetRankingInfo(global::Bbhrpc.GetRankingInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRankingInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetRankingInfoResponse GetRankingInfo(global::Bbhrpc.GetRankingInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRankingInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetRankingInfoResponse> GetRankingInfoAsync(global::Bbhrpc.GetRankingInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRankingInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetRankingInfoResponse> GetRankingInfoAsync(global::Bbhrpc.GetRankingInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRankingInfo, null, options, request);
      }
      public virtual global::Bbhrpc.GetRankingResponse GetRanking(global::Bbhrpc.GetRankingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRanking(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetRankingResponse GetRanking(global::Bbhrpc.GetRankingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRanking, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetRankingResponse> GetRankingAsync(global::Bbhrpc.GetRankingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRankingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetRankingResponse> GetRankingAsync(global::Bbhrpc.GetRankingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRanking, null, options, request);
      }
      public virtual global::Bbhrpc.ListRankingsResponse ListRankings(global::Bbhrpc.ListRankingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListRankings(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.ListRankingsResponse ListRankings(global::Bbhrpc.ListRankingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListRankings, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListRankingsResponse> ListRankingsAsync(global::Bbhrpc.ListRankingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListRankingsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListRankingsResponse> ListRankingsAsync(global::Bbhrpc.ListRankingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListRankings, null, options, request);
      }
      public virtual global::Bbhrpc.AddBountyResponse AddBounty(global::Bbhrpc.AddBountyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddBounty(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.AddBountyResponse AddBounty(global::Bbhrpc.AddBountyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddBounty, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.AddBountyResponse> AddBountyAsync(global::Bbhrpc.AddBountyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddBountyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.AddBountyResponse> AddBountyAsync(global::Bbhrpc.AddBountyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddBounty, null, options, request);
      }
      public virtual global::Bbhrpc.ListOnlineResponse ListOnline(global::Bbhrpc.ListOnlineRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListOnline(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.ListOnlineResponse ListOnline(global::Bbhrpc.ListOnlineRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListOnline, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListOnlineResponse> ListOnlineAsync(global::Bbhrpc.ListOnlineRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListOnlineAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListOnlineResponse> ListOnlineAsync(global::Bbhrpc.ListOnlineRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListOnline, null, options, request);
      }
      public virtual global::Bbhrpc.GetInfoResponse GetInfo(global::Bbhrpc.GetInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetInfo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetInfoResponse GetInfo(global::Bbhrpc.GetInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetInfo, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetInfoResponse> GetInfoAsync(global::Bbhrpc.GetInfoRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetInfoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetInfoResponse> GetInfoAsync(global::Bbhrpc.GetInfoRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetInfo, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Bbhrpc.SubscribeInvioceStreamResponse> SubscribeInvoiceStream(global::Bbhrpc.SubscribeInvoiceStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribeInvoiceStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Bbhrpc.SubscribeInvioceStreamResponse> SubscribeInvoiceStream(global::Bbhrpc.SubscribeInvoiceStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeInvoiceStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PublicServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PublicServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PublicServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRankingInfo, serviceImpl.GetRankingInfo)
          .AddMethod(__Method_GetRanking, serviceImpl.GetRanking)
          .AddMethod(__Method_ListRankings, serviceImpl.ListRankings)
          .AddMethod(__Method_AddBounty, serviceImpl.AddBounty)
          .AddMethod(__Method_ListOnline, serviceImpl.ListOnline)
          .AddMethod(__Method_GetInfo, serviceImpl.GetInfo)
          .AddMethod(__Method_SubscribeInvoiceStream, serviceImpl.SubscribeInvoiceStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PublicServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetRankingInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetRankingInfoRequest, global::Bbhrpc.GetRankingInfoResponse>(serviceImpl.GetRankingInfo));
      serviceBinder.AddMethod(__Method_GetRanking, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetRankingRequest, global::Bbhrpc.GetRankingResponse>(serviceImpl.GetRanking));
      serviceBinder.AddMethod(__Method_ListRankings, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.ListRankingsRequest, global::Bbhrpc.ListRankingsResponse>(serviceImpl.ListRankings));
      serviceBinder.AddMethod(__Method_AddBounty, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.AddBountyRequest, global::Bbhrpc.AddBountyResponse>(serviceImpl.AddBounty));
      serviceBinder.AddMethod(__Method_ListOnline, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.ListOnlineRequest, global::Bbhrpc.ListOnlineResponse>(serviceImpl.ListOnline));
      serviceBinder.AddMethod(__Method_GetInfo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetInfoRequest, global::Bbhrpc.GetInfoResponse>(serviceImpl.GetInfo));
      serviceBinder.AddMethod(__Method_SubscribeInvoiceStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Bbhrpc.SubscribeInvoiceStreamRequest, global::Bbhrpc.SubscribeInvioceStreamResponse>(serviceImpl.SubscribeInvoiceStream));
    }

  }
  public static partial class SkinService
  {
    static readonly string __ServiceName = "bbhrpc.SkinService";

    static readonly grpc::Marshaller<global::Bbhrpc.ListSkinsRequest> __Marshaller_bbhrpc_ListSkinsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListSkinsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.ListSkinsResponse> __Marshaller_bbhrpc_ListSkinsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.ListSkinsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.BuySkinRequest> __Marshaller_bbhrpc_BuySkinRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.BuySkinRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.BuySkinResponse> __Marshaller_bbhrpc_BuySkinResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.BuySkinResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetSkinInventoryRequest> __Marshaller_bbhrpc_GetSkinInventoryRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetSkinInventoryRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetSkinInventoryResponse> __Marshaller_bbhrpc_GetSkinInventoryResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetSkinInventoryResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.EquipSkinRequest> __Marshaller_bbhrpc_EquipSkinRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.EquipSkinRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.EquipSkinResponse> __Marshaller_bbhrpc_EquipSkinResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.EquipSkinResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Bbhrpc.ListSkinsRequest, global::Bbhrpc.ListSkinsResponse> __Method_ListSkins = new grpc::Method<global::Bbhrpc.ListSkinsRequest, global::Bbhrpc.ListSkinsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListSkins",
        __Marshaller_bbhrpc_ListSkinsRequest,
        __Marshaller_bbhrpc_ListSkinsResponse);

    static readonly grpc::Method<global::Bbhrpc.BuySkinRequest, global::Bbhrpc.BuySkinResponse> __Method_BuySkin = new grpc::Method<global::Bbhrpc.BuySkinRequest, global::Bbhrpc.BuySkinResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BuySkin",
        __Marshaller_bbhrpc_BuySkinRequest,
        __Marshaller_bbhrpc_BuySkinResponse);

    static readonly grpc::Method<global::Bbhrpc.GetSkinInventoryRequest, global::Bbhrpc.GetSkinInventoryResponse> __Method_GetSkinInventory = new grpc::Method<global::Bbhrpc.GetSkinInventoryRequest, global::Bbhrpc.GetSkinInventoryResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSkinInventory",
        __Marshaller_bbhrpc_GetSkinInventoryRequest,
        __Marshaller_bbhrpc_GetSkinInventoryResponse);

    static readonly grpc::Method<global::Bbhrpc.EquipSkinRequest, global::Bbhrpc.EquipSkinResponse> __Method_EquipSkin = new grpc::Method<global::Bbhrpc.EquipSkinRequest, global::Bbhrpc.EquipSkinResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EquipSkin",
        __Marshaller_bbhrpc_EquipSkinRequest,
        __Marshaller_bbhrpc_EquipSkinResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Bbhrpc.ClientReflection.Descriptor.Services[3]; }
    }

    /// <summary>Base class for server-side implementations of SkinService</summary>
    [grpc::BindServiceMethod(typeof(SkinService), "BindService")]
    public abstract partial class SkinServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.ListSkinsResponse> ListSkins(global::Bbhrpc.ListSkinsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.BuySkinResponse> BuySkin(global::Bbhrpc.BuySkinRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetSkinInventoryResponse> GetSkinInventory(global::Bbhrpc.GetSkinInventoryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.EquipSkinResponse> EquipSkin(global::Bbhrpc.EquipSkinRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SkinService</summary>
    public partial class SkinServiceClient : grpc::ClientBase<SkinServiceClient>
    {
      /// <summary>Creates a new client for SkinService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SkinServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SkinService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SkinServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SkinServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SkinServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Bbhrpc.ListSkinsResponse ListSkins(global::Bbhrpc.ListSkinsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListSkins(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.ListSkinsResponse ListSkins(global::Bbhrpc.ListSkinsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListSkins, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListSkinsResponse> ListSkinsAsync(global::Bbhrpc.ListSkinsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListSkinsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.ListSkinsResponse> ListSkinsAsync(global::Bbhrpc.ListSkinsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListSkins, null, options, request);
      }
      public virtual global::Bbhrpc.BuySkinResponse BuySkin(global::Bbhrpc.BuySkinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuySkin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.BuySkinResponse BuySkin(global::Bbhrpc.BuySkinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BuySkin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.BuySkinResponse> BuySkinAsync(global::Bbhrpc.BuySkinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuySkinAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.BuySkinResponse> BuySkinAsync(global::Bbhrpc.BuySkinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BuySkin, null, options, request);
      }
      public virtual global::Bbhrpc.GetSkinInventoryResponse GetSkinInventory(global::Bbhrpc.GetSkinInventoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSkinInventory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetSkinInventoryResponse GetSkinInventory(global::Bbhrpc.GetSkinInventoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSkinInventory, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetSkinInventoryResponse> GetSkinInventoryAsync(global::Bbhrpc.GetSkinInventoryRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSkinInventoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetSkinInventoryResponse> GetSkinInventoryAsync(global::Bbhrpc.GetSkinInventoryRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSkinInventory, null, options, request);
      }
      public virtual global::Bbhrpc.EquipSkinResponse EquipSkin(global::Bbhrpc.EquipSkinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EquipSkin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.EquipSkinResponse EquipSkin(global::Bbhrpc.EquipSkinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EquipSkin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.EquipSkinResponse> EquipSkinAsync(global::Bbhrpc.EquipSkinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EquipSkinAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.EquipSkinResponse> EquipSkinAsync(global::Bbhrpc.EquipSkinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EquipSkin, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SkinServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SkinServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SkinServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListSkins, serviceImpl.ListSkins)
          .AddMethod(__Method_BuySkin, serviceImpl.BuySkin)
          .AddMethod(__Method_GetSkinInventory, serviceImpl.GetSkinInventory)
          .AddMethod(__Method_EquipSkin, serviceImpl.EquipSkin).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SkinServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ListSkins, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.ListSkinsRequest, global::Bbhrpc.ListSkinsResponse>(serviceImpl.ListSkins));
      serviceBinder.AddMethod(__Method_BuySkin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.BuySkinRequest, global::Bbhrpc.BuySkinResponse>(serviceImpl.BuySkin));
      serviceBinder.AddMethod(__Method_GetSkinInventory, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetSkinInventoryRequest, global::Bbhrpc.GetSkinInventoryResponse>(serviceImpl.GetSkinInventory));
      serviceBinder.AddMethod(__Method_EquipSkin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.EquipSkinRequest, global::Bbhrpc.EquipSkinResponse>(serviceImpl.EquipSkin));
    }

  }
}
#endregion
