// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bbh-backend/gameserver.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Bbhrpc {
  public static partial class GameServerService
  {
    static readonly string __ServiceName = "bbhrpc.GameServerService";

    static readonly grpc::Marshaller<global::Bbhrpc.EventStreamRequest> __Marshaller_bbhrpc_EventStreamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.EventStreamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.EventStreamResponse> __Marshaller_bbhrpc_EventStreamResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.EventStreamResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.BackendStreamRequest> __Marshaller_bbhrpc_BackendStreamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.BackendStreamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.BackendStreamResponse> __Marshaller_bbhrpc_BackendStreamResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.BackendStreamResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetUserRequest> __Marshaller_bbhrpc_GetUserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetUserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetUserResponse> __Marshaller_bbhrpc_GetUserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetUserResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetUserSkinRequest> __Marshaller_bbhrpc_GetUserSkinRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetUserSkinRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetUserSkinResponse> __Marshaller_bbhrpc_GetUserSkinResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetUserSkinResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetAdvertisersRequest> __Marshaller_bbhrpc_GetAdvertisersRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetAdvertisersRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetAdvertisersResponse> __Marshaller_bbhrpc_GetAdvertisersResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetAdvertisersResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetGameModeSettingsRequest> __Marshaller_bbhrpc_GetGameModeSettingsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetGameModeSettingsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.GetGameModeSettingsResponse> __Marshaller_bbhrpc_GetGameModeSettingsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.GetGameModeSettingsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.PostStatsRequest> __Marshaller_bbhrpc_PostStatsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.PostStatsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.PostStatsResponse> __Marshaller_bbhrpc_PostStatsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.PostStatsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.EndRoomRequest> __Marshaller_bbhrpc_EndRoomRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.EndRoomRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Bbhrpc.EndRoomResponse> __Marshaller_bbhrpc_EndRoomResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Bbhrpc.EndRoomResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Bbhrpc.EventStreamRequest, global::Bbhrpc.EventStreamResponse> __Method_EventStream = new grpc::Method<global::Bbhrpc.EventStreamRequest, global::Bbhrpc.EventStreamResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "EventStream",
        __Marshaller_bbhrpc_EventStreamRequest,
        __Marshaller_bbhrpc_EventStreamResponse);

    static readonly grpc::Method<global::Bbhrpc.BackendStreamRequest, global::Bbhrpc.BackendStreamResponse> __Method_BackendStream = new grpc::Method<global::Bbhrpc.BackendStreamRequest, global::Bbhrpc.BackendStreamResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "BackendStream",
        __Marshaller_bbhrpc_BackendStreamRequest,
        __Marshaller_bbhrpc_BackendStreamResponse);

    static readonly grpc::Method<global::Bbhrpc.GetUserRequest, global::Bbhrpc.GetUserResponse> __Method_GetUser = new grpc::Method<global::Bbhrpc.GetUserRequest, global::Bbhrpc.GetUserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUser",
        __Marshaller_bbhrpc_GetUserRequest,
        __Marshaller_bbhrpc_GetUserResponse);

    static readonly grpc::Method<global::Bbhrpc.GetUserSkinRequest, global::Bbhrpc.GetUserSkinResponse> __Method_GetUserSkin = new grpc::Method<global::Bbhrpc.GetUserSkinRequest, global::Bbhrpc.GetUserSkinResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetUserSkin",
        __Marshaller_bbhrpc_GetUserSkinRequest,
        __Marshaller_bbhrpc_GetUserSkinResponse);

    static readonly grpc::Method<global::Bbhrpc.GetAdvertisersRequest, global::Bbhrpc.GetAdvertisersResponse> __Method_GetAdvertisers = new grpc::Method<global::Bbhrpc.GetAdvertisersRequest, global::Bbhrpc.GetAdvertisersResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAdvertisers",
        __Marshaller_bbhrpc_GetAdvertisersRequest,
        __Marshaller_bbhrpc_GetAdvertisersResponse);

    static readonly grpc::Method<global::Bbhrpc.GetGameModeSettingsRequest, global::Bbhrpc.GetGameModeSettingsResponse> __Method_GetGameModeSettings = new grpc::Method<global::Bbhrpc.GetGameModeSettingsRequest, global::Bbhrpc.GetGameModeSettingsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetGameModeSettings",
        __Marshaller_bbhrpc_GetGameModeSettingsRequest,
        __Marshaller_bbhrpc_GetGameModeSettingsResponse);

    static readonly grpc::Method<global::Bbhrpc.PostStatsRequest, global::Bbhrpc.PostStatsResponse> __Method_PostStats = new grpc::Method<global::Bbhrpc.PostStatsRequest, global::Bbhrpc.PostStatsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PostStats",
        __Marshaller_bbhrpc_PostStatsRequest,
        __Marshaller_bbhrpc_PostStatsResponse);

    static readonly grpc::Method<global::Bbhrpc.EndRoomRequest, global::Bbhrpc.EndRoomResponse> __Method_EndRoom = new grpc::Method<global::Bbhrpc.EndRoomRequest, global::Bbhrpc.EndRoomResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EndRoom",
        __Marshaller_bbhrpc_EndRoomRequest,
        __Marshaller_bbhrpc_EndRoomResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Bbhrpc.GameserverReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GameServerService</summary>
    [grpc::BindServiceMethod(typeof(GameServerService), "BindService")]
    public abstract partial class GameServerServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.EventStreamResponse> EventStream(grpc::IAsyncStreamReader<global::Bbhrpc.EventStreamRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task BackendStream(global::Bbhrpc.BackendStreamRequest request, grpc::IServerStreamWriter<global::Bbhrpc.BackendStreamResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetUserResponse> GetUser(global::Bbhrpc.GetUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetUserSkinResponse> GetUserSkin(global::Bbhrpc.GetUserSkinRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetAdvertisersResponse> GetAdvertisers(global::Bbhrpc.GetAdvertisersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.GetGameModeSettingsResponse> GetGameModeSettings(global::Bbhrpc.GetGameModeSettingsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.PostStatsResponse> PostStats(global::Bbhrpc.PostStatsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Bbhrpc.EndRoomResponse> EndRoom(global::Bbhrpc.EndRoomRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GameServerService</summary>
    public partial class GameServerServiceClient : grpc::ClientBase<GameServerServiceClient>
    {
      /// <summary>Creates a new client for GameServerService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GameServerServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GameServerService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GameServerServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GameServerServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GameServerServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncClientStreamingCall<global::Bbhrpc.EventStreamRequest, global::Bbhrpc.EventStreamResponse> EventStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EventStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Bbhrpc.EventStreamRequest, global::Bbhrpc.EventStreamResponse> EventStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_EventStream, null, options);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Bbhrpc.BackendStreamResponse> BackendStream(global::Bbhrpc.BackendStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BackendStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Bbhrpc.BackendStreamResponse> BackendStream(global::Bbhrpc.BackendStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_BackendStream, null, options, request);
      }
      public virtual global::Bbhrpc.GetUserResponse GetUser(global::Bbhrpc.GetUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetUserResponse GetUser(global::Bbhrpc.GetUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUser, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetUserResponse> GetUserAsync(global::Bbhrpc.GetUserRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetUserResponse> GetUserAsync(global::Bbhrpc.GetUserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUser, null, options, request);
      }
      public virtual global::Bbhrpc.GetUserSkinResponse GetUserSkin(global::Bbhrpc.GetUserSkinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserSkin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetUserSkinResponse GetUserSkin(global::Bbhrpc.GetUserSkinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetUserSkin, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetUserSkinResponse> GetUserSkinAsync(global::Bbhrpc.GetUserSkinRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetUserSkinAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetUserSkinResponse> GetUserSkinAsync(global::Bbhrpc.GetUserSkinRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetUserSkin, null, options, request);
      }
      public virtual global::Bbhrpc.GetAdvertisersResponse GetAdvertisers(global::Bbhrpc.GetAdvertisersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAdvertisers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetAdvertisersResponse GetAdvertisers(global::Bbhrpc.GetAdvertisersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAdvertisers, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetAdvertisersResponse> GetAdvertisersAsync(global::Bbhrpc.GetAdvertisersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAdvertisersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetAdvertisersResponse> GetAdvertisersAsync(global::Bbhrpc.GetAdvertisersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAdvertisers, null, options, request);
      }
      public virtual global::Bbhrpc.GetGameModeSettingsResponse GetGameModeSettings(global::Bbhrpc.GetGameModeSettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGameModeSettings(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.GetGameModeSettingsResponse GetGameModeSettings(global::Bbhrpc.GetGameModeSettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetGameModeSettings, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetGameModeSettingsResponse> GetGameModeSettingsAsync(global::Bbhrpc.GetGameModeSettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetGameModeSettingsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.GetGameModeSettingsResponse> GetGameModeSettingsAsync(global::Bbhrpc.GetGameModeSettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetGameModeSettings, null, options, request);
      }
      public virtual global::Bbhrpc.PostStatsResponse PostStats(global::Bbhrpc.PostStatsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostStats(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.PostStatsResponse PostStats(global::Bbhrpc.PostStatsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PostStats, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.PostStatsResponse> PostStatsAsync(global::Bbhrpc.PostStatsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostStatsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.PostStatsResponse> PostStatsAsync(global::Bbhrpc.PostStatsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PostStats, null, options, request);
      }
      public virtual global::Bbhrpc.EndRoomResponse EndRoom(global::Bbhrpc.EndRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EndRoom(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Bbhrpc.EndRoomResponse EndRoom(global::Bbhrpc.EndRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_EndRoom, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.EndRoomResponse> EndRoomAsync(global::Bbhrpc.EndRoomRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EndRoomAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Bbhrpc.EndRoomResponse> EndRoomAsync(global::Bbhrpc.EndRoomRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_EndRoom, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GameServerServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GameServerServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GameServerServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_EventStream, serviceImpl.EventStream)
          .AddMethod(__Method_BackendStream, serviceImpl.BackendStream)
          .AddMethod(__Method_GetUser, serviceImpl.GetUser)
          .AddMethod(__Method_GetUserSkin, serviceImpl.GetUserSkin)
          .AddMethod(__Method_GetAdvertisers, serviceImpl.GetAdvertisers)
          .AddMethod(__Method_GetGameModeSettings, serviceImpl.GetGameModeSettings)
          .AddMethod(__Method_PostStats, serviceImpl.PostStats)
          .AddMethod(__Method_EndRoom, serviceImpl.EndRoom).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GameServerServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_EventStream, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Bbhrpc.EventStreamRequest, global::Bbhrpc.EventStreamResponse>(serviceImpl.EventStream));
      serviceBinder.AddMethod(__Method_BackendStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Bbhrpc.BackendStreamRequest, global::Bbhrpc.BackendStreamResponse>(serviceImpl.BackendStream));
      serviceBinder.AddMethod(__Method_GetUser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetUserRequest, global::Bbhrpc.GetUserResponse>(serviceImpl.GetUser));
      serviceBinder.AddMethod(__Method_GetUserSkin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetUserSkinRequest, global::Bbhrpc.GetUserSkinResponse>(serviceImpl.GetUserSkin));
      serviceBinder.AddMethod(__Method_GetAdvertisers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetAdvertisersRequest, global::Bbhrpc.GetAdvertisersResponse>(serviceImpl.GetAdvertisers));
      serviceBinder.AddMethod(__Method_GetGameModeSettings, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.GetGameModeSettingsRequest, global::Bbhrpc.GetGameModeSettingsResponse>(serviceImpl.GetGameModeSettings));
      serviceBinder.AddMethod(__Method_PostStats, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.PostStatsRequest, global::Bbhrpc.PostStatsResponse>(serviceImpl.PostStats));
      serviceBinder.AddMethod(__Method_EndRoom, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Bbhrpc.EndRoomRequest, global::Bbhrpc.EndRoomResponse>(serviceImpl.EndRoom));
    }

  }
}
#endregion
