// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: daemon.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Daemon {

  /// <summary>Holder for reflection information generated from daemon.proto</summary>
  public static partial class DaemonReflection {

    #region Descriptor
    /// <summary>File descriptor for daemon.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DaemonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxkYWVtb24ucHJvdG8SBmRhZW1vbiIfCgxMbmNsaVJlcXVlc3QSDwoHY29t",
            "bWFuZBgBIAEoCSImCg1MbmNsaVJlc3BvbnNlEhUKDXRleHRfcmVzcG9uc2UY",
            "AiABKAkiEAoOR2V0SW5mb1JlcXVlc3QiZgoPR2V0SW5mb1Jlc3BvbnNlEhIK",
            "Cm5vZGVfYWxpdmUYASABKAgSEwoLbm9kZV9wdWJrZXkYAiABKAkSFAoMY2hh",
            "bm5lbF9vcGVuGAMgASgIEhQKDGNoYW5uZWxfc3luYxgEIAEoCCIWChRHZXRD",
            "b25uZWN0aW9uUmVxdWVzdCKAAQoVR2V0Q29ubmVjdGlvblJlc3BvbnNlEhIK",
            "Cm5vZGVfYWxpdmUYASABKAgSFAoMZ3JwY19hZGRyZXNzGAIgASgJEhMKC3Ay",
            "cF9hZGRyZXNzGAMgASgJEhEKCWNlcnRfcGF0aBgEIAEoCRIVCg1tYWNhcm9v",
            "bl9wYXRoGAUgASgJIjgKFENyZWF0ZUludm9pY2VSZXF1ZXN0EgsKA2FtdBgB",
            "IAEoAxITCgtkZXNjcmlwdGlvbhgCIAEoCSIoChVDcmVhdGVJbnZvaWNlUmVz",
            "cG9uc2USDwoHaW52b2ljZRgBIAEoCSIcChpQbGF0Zm9ybUNoYW5uZWxJbmZv",
            "UmVxdWVzdCJpChtQbGF0Zm9ybUNoYW5uZWxJbmZvUmVzcG9uc2USDgoGc3Rh",
            "dHVzGAEgASgJEhUKDWxvY2FsX2JhbGFuY2UYAiABKAMSFgoOcmVtb3RlX2Jh",
            "bGFuY2UYAyABKAMSCwoDZXRhGAQgASgDMv8CCg1EYWVtb25TZXJ2aWNlEjQK",
            "BUxuY2xpEhQuZGFlbW9uLkxuY2xpUmVxdWVzdBoVLmRhZW1vbi5MbmNsaVJl",
            "c3BvbnNlEjoKB0dldEluZm8SFi5kYWVtb24uR2V0SW5mb1JlcXVlc3QaFy5k",
            "YWVtb24uR2V0SW5mb1Jlc3BvbnNlEkwKDUdldENvbm5lY3Rpb24SHC5kYWVt",
            "b24uR2V0Q29ubmVjdGlvblJlcXVlc3QaHS5kYWVtb24uR2V0Q29ubmVjdGlv",
            "blJlc3BvbnNlEkwKDUNyZWF0ZUludm9pY2USHC5kYWVtb24uQ3JlYXRlSW52",
            "b2ljZVJlcXVlc3QaHS5kYWVtb24uQ3JlYXRlSW52b2ljZVJlc3BvbnNlEmAK",
            "E1BsYXRmb3JtQ2hhbm5lbEluZm8SIi5kYWVtb24uUGxhdGZvcm1DaGFubmVs",
            "SW5mb1JlcXVlc3QaIy5kYWVtb24uUGxhdGZvcm1DaGFubmVsSW5mb1Jlc3Bv",
            "bnNlMAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.LncliRequest), global::Daemon.LncliRequest.Parser, new[]{ "Command" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.LncliResponse), global::Daemon.LncliResponse.Parser, new[]{ "TextResponse" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.GetInfoRequest), global::Daemon.GetInfoRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.GetInfoResponse), global::Daemon.GetInfoResponse.Parser, new[]{ "NodeAlive", "NodePubkey", "ChannelOpen", "ChannelSync" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.GetConnectionRequest), global::Daemon.GetConnectionRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.GetConnectionResponse), global::Daemon.GetConnectionResponse.Parser, new[]{ "NodeAlive", "GrpcAddress", "P2PAddress", "CertPath", "MacaroonPath" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.CreateInvoiceRequest), global::Daemon.CreateInvoiceRequest.Parser, new[]{ "Amt", "Description" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.CreateInvoiceResponse), global::Daemon.CreateInvoiceResponse.Parser, new[]{ "Invoice" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.PlatformChannelInfoRequest), global::Daemon.PlatformChannelInfoRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Daemon.PlatformChannelInfoResponse), global::Daemon.PlatformChannelInfoResponse.Parser, new[]{ "Status", "LocalBalance", "RemoteBalance", "Eta" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LncliRequest : pb::IMessage<LncliRequest> {
    private static readonly pb::MessageParser<LncliRequest> _parser = new pb::MessageParser<LncliRequest>(() => new LncliRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LncliRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LncliRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LncliRequest(LncliRequest other) : this() {
      command_ = other.command_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LncliRequest Clone() {
      return new LncliRequest(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 1;
    private string command_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Command {
      get { return command_; }
      set {
        command_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LncliRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LncliRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Command != other.Command) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Command.Length != 0) hash ^= Command.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Command.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Command.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Command);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LncliRequest other) {
      if (other == null) {
        return;
      }
      if (other.Command.Length != 0) {
        Command = other.Command;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Command = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LncliResponse : pb::IMessage<LncliResponse> {
    private static readonly pb::MessageParser<LncliResponse> _parser = new pb::MessageParser<LncliResponse>(() => new LncliResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LncliResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LncliResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LncliResponse(LncliResponse other) : this() {
      textResponse_ = other.textResponse_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LncliResponse Clone() {
      return new LncliResponse(this);
    }

    /// <summary>Field number for the "text_response" field.</summary>
    public const int TextResponseFieldNumber = 2;
    private string textResponse_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextResponse {
      get { return textResponse_; }
      set {
        textResponse_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LncliResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LncliResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TextResponse != other.TextResponse) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TextResponse.Length != 0) hash ^= TextResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TextResponse.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TextResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TextResponse.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LncliResponse other) {
      if (other == null) {
        return;
      }
      if (other.TextResponse.Length != 0) {
        TextResponse = other.TextResponse;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            TextResponse = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetInfoRequest : pb::IMessage<GetInfoRequest> {
    private static readonly pb::MessageParser<GetInfoRequest> _parser = new pb::MessageParser<GetInfoRequest>(() => new GetInfoRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetInfoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInfoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInfoRequest(GetInfoRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInfoRequest Clone() {
      return new GetInfoRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetInfoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetInfoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetInfoRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GetInfoResponse : pb::IMessage<GetInfoResponse> {
    private static readonly pb::MessageParser<GetInfoResponse> _parser = new pb::MessageParser<GetInfoResponse>(() => new GetInfoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetInfoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInfoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInfoResponse(GetInfoResponse other) : this() {
      nodeAlive_ = other.nodeAlive_;
      nodePubkey_ = other.nodePubkey_;
      channelOpen_ = other.channelOpen_;
      channelSync_ = other.channelSync_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetInfoResponse Clone() {
      return new GetInfoResponse(this);
    }

    /// <summary>Field number for the "node_alive" field.</summary>
    public const int NodeAliveFieldNumber = 1;
    private bool nodeAlive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool NodeAlive {
      get { return nodeAlive_; }
      set {
        nodeAlive_ = value;
      }
    }

    /// <summary>Field number for the "node_pubkey" field.</summary>
    public const int NodePubkeyFieldNumber = 2;
    private string nodePubkey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NodePubkey {
      get { return nodePubkey_; }
      set {
        nodePubkey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "channel_open" field.</summary>
    public const int ChannelOpenFieldNumber = 3;
    private bool channelOpen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ChannelOpen {
      get { return channelOpen_; }
      set {
        channelOpen_ = value;
      }
    }

    /// <summary>Field number for the "channel_sync" field.</summary>
    public const int ChannelSyncFieldNumber = 4;
    private bool channelSync_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ChannelSync {
      get { return channelSync_; }
      set {
        channelSync_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetInfoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetInfoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NodeAlive != other.NodeAlive) return false;
      if (NodePubkey != other.NodePubkey) return false;
      if (ChannelOpen != other.ChannelOpen) return false;
      if (ChannelSync != other.ChannelSync) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NodeAlive != false) hash ^= NodeAlive.GetHashCode();
      if (NodePubkey.Length != 0) hash ^= NodePubkey.GetHashCode();
      if (ChannelOpen != false) hash ^= ChannelOpen.GetHashCode();
      if (ChannelSync != false) hash ^= ChannelSync.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NodeAlive != false) {
        output.WriteRawTag(8);
        output.WriteBool(NodeAlive);
      }
      if (NodePubkey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NodePubkey);
      }
      if (ChannelOpen != false) {
        output.WriteRawTag(24);
        output.WriteBool(ChannelOpen);
      }
      if (ChannelSync != false) {
        output.WriteRawTag(32);
        output.WriteBool(ChannelSync);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NodeAlive != false) {
        size += 1 + 1;
      }
      if (NodePubkey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NodePubkey);
      }
      if (ChannelOpen != false) {
        size += 1 + 1;
      }
      if (ChannelSync != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetInfoResponse other) {
      if (other == null) {
        return;
      }
      if (other.NodeAlive != false) {
        NodeAlive = other.NodeAlive;
      }
      if (other.NodePubkey.Length != 0) {
        NodePubkey = other.NodePubkey;
      }
      if (other.ChannelOpen != false) {
        ChannelOpen = other.ChannelOpen;
      }
      if (other.ChannelSync != false) {
        ChannelSync = other.ChannelSync;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NodeAlive = input.ReadBool();
            break;
          }
          case 18: {
            NodePubkey = input.ReadString();
            break;
          }
          case 24: {
            ChannelOpen = input.ReadBool();
            break;
          }
          case 32: {
            ChannelSync = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetConnectionRequest : pb::IMessage<GetConnectionRequest> {
    private static readonly pb::MessageParser<GetConnectionRequest> _parser = new pb::MessageParser<GetConnectionRequest>(() => new GetConnectionRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetConnectionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetConnectionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetConnectionRequest(GetConnectionRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetConnectionRequest Clone() {
      return new GetConnectionRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetConnectionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetConnectionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetConnectionRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GetConnectionResponse : pb::IMessage<GetConnectionResponse> {
    private static readonly pb::MessageParser<GetConnectionResponse> _parser = new pb::MessageParser<GetConnectionResponse>(() => new GetConnectionResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetConnectionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetConnectionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetConnectionResponse(GetConnectionResponse other) : this() {
      nodeAlive_ = other.nodeAlive_;
      grpcAddress_ = other.grpcAddress_;
      p2PAddress_ = other.p2PAddress_;
      certPath_ = other.certPath_;
      macaroonPath_ = other.macaroonPath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetConnectionResponse Clone() {
      return new GetConnectionResponse(this);
    }

    /// <summary>Field number for the "node_alive" field.</summary>
    public const int NodeAliveFieldNumber = 1;
    private bool nodeAlive_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool NodeAlive {
      get { return nodeAlive_; }
      set {
        nodeAlive_ = value;
      }
    }

    /// <summary>Field number for the "grpc_address" field.</summary>
    public const int GrpcAddressFieldNumber = 2;
    private string grpcAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string GrpcAddress {
      get { return grpcAddress_; }
      set {
        grpcAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "p2p_address" field.</summary>
    public const int P2PAddressFieldNumber = 3;
    private string p2PAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string P2PAddress {
      get { return p2PAddress_; }
      set {
        p2PAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cert_path" field.</summary>
    public const int CertPathFieldNumber = 4;
    private string certPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CertPath {
      get { return certPath_; }
      set {
        certPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "macaroon_path" field.</summary>
    public const int MacaroonPathFieldNumber = 5;
    private string macaroonPath_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MacaroonPath {
      get { return macaroonPath_; }
      set {
        macaroonPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetConnectionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetConnectionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NodeAlive != other.NodeAlive) return false;
      if (GrpcAddress != other.GrpcAddress) return false;
      if (P2PAddress != other.P2PAddress) return false;
      if (CertPath != other.CertPath) return false;
      if (MacaroonPath != other.MacaroonPath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NodeAlive != false) hash ^= NodeAlive.GetHashCode();
      if (GrpcAddress.Length != 0) hash ^= GrpcAddress.GetHashCode();
      if (P2PAddress.Length != 0) hash ^= P2PAddress.GetHashCode();
      if (CertPath.Length != 0) hash ^= CertPath.GetHashCode();
      if (MacaroonPath.Length != 0) hash ^= MacaroonPath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NodeAlive != false) {
        output.WriteRawTag(8);
        output.WriteBool(NodeAlive);
      }
      if (GrpcAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(GrpcAddress);
      }
      if (P2PAddress.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(P2PAddress);
      }
      if (CertPath.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CertPath);
      }
      if (MacaroonPath.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MacaroonPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NodeAlive != false) {
        size += 1 + 1;
      }
      if (GrpcAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GrpcAddress);
      }
      if (P2PAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(P2PAddress);
      }
      if (CertPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CertPath);
      }
      if (MacaroonPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MacaroonPath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetConnectionResponse other) {
      if (other == null) {
        return;
      }
      if (other.NodeAlive != false) {
        NodeAlive = other.NodeAlive;
      }
      if (other.GrpcAddress.Length != 0) {
        GrpcAddress = other.GrpcAddress;
      }
      if (other.P2PAddress.Length != 0) {
        P2PAddress = other.P2PAddress;
      }
      if (other.CertPath.Length != 0) {
        CertPath = other.CertPath;
      }
      if (other.MacaroonPath.Length != 0) {
        MacaroonPath = other.MacaroonPath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NodeAlive = input.ReadBool();
            break;
          }
          case 18: {
            GrpcAddress = input.ReadString();
            break;
          }
          case 26: {
            P2PAddress = input.ReadString();
            break;
          }
          case 34: {
            CertPath = input.ReadString();
            break;
          }
          case 42: {
            MacaroonPath = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateInvoiceRequest : pb::IMessage<CreateInvoiceRequest> {
    private static readonly pb::MessageParser<CreateInvoiceRequest> _parser = new pb::MessageParser<CreateInvoiceRequest>(() => new CreateInvoiceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateInvoiceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateInvoiceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateInvoiceRequest(CreateInvoiceRequest other) : this() {
      amt_ = other.amt_;
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateInvoiceRequest Clone() {
      return new CreateInvoiceRequest(this);
    }

    /// <summary>Field number for the "amt" field.</summary>
    public const int AmtFieldNumber = 1;
    private long amt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Amt {
      get { return amt_; }
      set {
        amt_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 2;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateInvoiceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateInvoiceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Amt != other.Amt) return false;
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Amt != 0L) hash ^= Amt.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Amt != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Amt);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Amt != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Amt);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateInvoiceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Amt != 0L) {
        Amt = other.Amt;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Amt = input.ReadInt64();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CreateInvoiceResponse : pb::IMessage<CreateInvoiceResponse> {
    private static readonly pb::MessageParser<CreateInvoiceResponse> _parser = new pb::MessageParser<CreateInvoiceResponse>(() => new CreateInvoiceResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateInvoiceResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateInvoiceResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateInvoiceResponse(CreateInvoiceResponse other) : this() {
      invoice_ = other.invoice_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateInvoiceResponse Clone() {
      return new CreateInvoiceResponse(this);
    }

    /// <summary>Field number for the "invoice" field.</summary>
    public const int InvoiceFieldNumber = 1;
    private string invoice_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Invoice {
      get { return invoice_; }
      set {
        invoice_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateInvoiceResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateInvoiceResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Invoice != other.Invoice) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Invoice.Length != 0) hash ^= Invoice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Invoice.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Invoice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Invoice.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Invoice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateInvoiceResponse other) {
      if (other == null) {
        return;
      }
      if (other.Invoice.Length != 0) {
        Invoice = other.Invoice;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Invoice = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlatformChannelInfoRequest : pb::IMessage<PlatformChannelInfoRequest> {
    private static readonly pb::MessageParser<PlatformChannelInfoRequest> _parser = new pb::MessageParser<PlatformChannelInfoRequest>(() => new PlatformChannelInfoRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlatformChannelInfoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformChannelInfoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformChannelInfoRequest(PlatformChannelInfoRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformChannelInfoRequest Clone() {
      return new PlatformChannelInfoRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlatformChannelInfoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlatformChannelInfoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlatformChannelInfoRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class PlatformChannelInfoResponse : pb::IMessage<PlatformChannelInfoResponse> {
    private static readonly pb::MessageParser<PlatformChannelInfoResponse> _parser = new pb::MessageParser<PlatformChannelInfoResponse>(() => new PlatformChannelInfoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlatformChannelInfoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Daemon.DaemonReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformChannelInfoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformChannelInfoResponse(PlatformChannelInfoResponse other) : this() {
      status_ = other.status_;
      localBalance_ = other.localBalance_;
      remoteBalance_ = other.remoteBalance_;
      eta_ = other.eta_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformChannelInfoResponse Clone() {
      return new PlatformChannelInfoResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "local_balance" field.</summary>
    public const int LocalBalanceFieldNumber = 2;
    private long localBalance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long LocalBalance {
      get { return localBalance_; }
      set {
        localBalance_ = value;
      }
    }

    /// <summary>Field number for the "remote_balance" field.</summary>
    public const int RemoteBalanceFieldNumber = 3;
    private long remoteBalance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RemoteBalance {
      get { return remoteBalance_; }
      set {
        remoteBalance_ = value;
      }
    }

    /// <summary>Field number for the "eta" field.</summary>
    public const int EtaFieldNumber = 4;
    private long eta_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Eta {
      get { return eta_; }
      set {
        eta_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlatformChannelInfoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlatformChannelInfoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (LocalBalance != other.LocalBalance) return false;
      if (RemoteBalance != other.RemoteBalance) return false;
      if (Eta != other.Eta) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (LocalBalance != 0L) hash ^= LocalBalance.GetHashCode();
      if (RemoteBalance != 0L) hash ^= RemoteBalance.GetHashCode();
      if (Eta != 0L) hash ^= Eta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Status);
      }
      if (LocalBalance != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(LocalBalance);
      }
      if (RemoteBalance != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RemoteBalance);
      }
      if (Eta != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Eta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (LocalBalance != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LocalBalance);
      }
      if (RemoteBalance != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RemoteBalance);
      }
      if (Eta != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Eta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlatformChannelInfoResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      if (other.LocalBalance != 0L) {
        LocalBalance = other.LocalBalance;
      }
      if (other.RemoteBalance != 0L) {
        RemoteBalance = other.RemoteBalance;
      }
      if (other.Eta != 0L) {
        Eta = other.Eta;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Status = input.ReadString();
            break;
          }
          case 16: {
            LocalBalance = input.ReadInt64();
            break;
          }
          case 24: {
            RemoteBalance = input.ReadInt64();
            break;
          }
          case 32: {
            Eta = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
